apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-wait-fail

resources:
- namespace.yaml
- ../../_example_app

images:
  - name: nginx
    newName: doesnotexist/definitelydoesntexist
