apiVersion: test.example.com/v1alpha1
kind: Namespacedcrd
metadata:
  name: namespacedco
  namespace: test-crd
spec: {}
---
apiVersion: test.example.com/v1alpha1
kind: Clusteredcrd
metadata:
  name: clusteredco
spec: {}
