apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespacedcrds.test.example.com
spec:
  group: test.example.com
  names:
    kind: Namespacedcrd
    plural: namespacedcrds
    shortNames:
    - ncrds
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteredcrds.test.example.com
spec:
  group: test.example.com
  names:
    kind: Clusteredcrd
    plural: clusteredcrds
    shortNames:
    - ccrds
  scope: Cluster
  version: v1alpha1
