apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "test-basic.name" . }}
  name: {{ include "test-basic.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "test-basic.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "test-basic.name" . }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name : {{ .Chart.Name }}
