apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "test-basic.name" . }}
  name: {{ include "test-basic.name" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.nginx.port }}
    protocol: TCP
    targetPort: {{ .Values.nginx.port }}
  selector:
    app: {{ include "test-basic.name" . }}
  type: ClusterIP
